### ISSUE TITLE
Add All Contributors

### ISSUE THREAD

**Issue by navin-moorthy** [timelessco/chakra-components#10]
We will be adding [All Contributor Bot](https://allcontributors.org/) to organize our contributors

Read the [All Contributors Docs](https://allcontributors.org/docs/en/overview) to get an overview on how to install the bot and use them

**Comment by navin-moorthy** [comment]
@all-contributors please add @navin-moorthy for code

**Comment by navin-moorthy** [comment]
@prasanna1211 All-Contributors is by default raising pull-request to only `master` branch.
Is it okay to merge this in master?
I checked on this issue - there is already an [issue](https://github.com/all-contributors/all-contributors-bot/issues/243) for this.

**Comment by prasanna1211** [comment]
Yes merge with master.

**Comment by navin-moorthy** [comment]
@all-contributors please add @govindsingh55 for code

**Comment by navin-moorthy** [comment]
@all-contributors please add @SamrithaS for code

**Comment by navin-moorthy** [comment]
@all-contributors please add @prasanna1211 for review
