### ISSUE TITLE
Add story book

### ISSUE THREAD

**Issue by prasanna1211** [timelessco/chakra-components#12]
Would prefer [storybook](https://storybook.js.org/) library.

1. Should be able to import and show demo of the component
2. Should be able to custom style the component (preferably using our components).

**Comment by prasanna1211** [comment]
`npm run start` should start the story book instead of index.js of the app. index.js should be just the root for the npm package.

**Comment by navin-moorthy** [comment]
> 1. `npm run start` should start the story book

Okay I will configure like that

**Comment by navin-moorthy** [comment]
Finished adding the storybook to our checkbox component.

**Comment by prasanna1211** [comment]
Moved to story book with DOCZ library.
