### ISSUE TITLE
React Boilerplate

### ISSUE THREAD

**Issue by SamrithaS** [timelessco/chakra-components#2]
We are using [React Boilerplate](https://github.com/react-boilerplate/react-boilerplate) as a boilerplate because it has webpack.config for prod and development exposed which helps customizations

**Comment by SamrithaS** [comment]
we are using [https://github.com/react-boilerplate/react-boilerplate](url) as a boiler plate because it has webpack.config for prod and development exposed which helps customizations

**Comment by prasanna1211** [comment]
Test

**Comment by prasanna1211** [comment]
Who is taking up this issue ? Please assign themselves. 

**Responsiblities**: Should include that boilerplate with proper `.gitignore` and push it in a new branch + Raise a PR.

**Comment by navin-moorthy** [comment]
I will assign it to myself and add proper .gitignore
