### ISSUE TITLE
[RFC] Text Component

### ISSUE THREAD

**Issue by SamrithaS** [timelessco/chakra-components#5]
**Introduction**
Text is used to render text and paragraphs within an interface. Text is derived from` Box `component as a paragraph `<p>` and it can take all styles that `Box` does

**Props**

- fontSize
- fontFamily
- Color
- fontWeight 
- lineHeight 
- letterSpacing 
- textAlign 
- fontStyle 
- textTransform 
- textDecoration
- m
- mt
- mb
- mr
- ml
- mx
- my
- p
- pt
- pb
- pr
- pl
- px
- py
- va
- ha

**Comment by prasanna1211** [comment]
as per chakra, Text is a dependency of box and rendered as p tag. Read [this](https://github.com/chakra-ui/chakra-ui/blob/master/packages/chakra-ui/src/Text/index.js)

**Comment by SamrithaS** [comment]
@prasanna1211  okay read it, Is there any change that I should impose in this RFC?

**Comment by prasanna1211** [comment]
No. Box component becomes a dependency for this. So lets wrap Box, then Text then Button.

**Comment by navin-moorthy** [comment]
Is Button built on top of Box and Text?
Why can't this be a separate one? In chakra it is built on top of PseudoBox.

**Comment by prasanna1211** [comment]
Primarily to commonize props. So any component that uses box will have same prop definitions throughout. They have Box as lower level primitive. Box has 'as' props which gives flexiblity to render it as anything.

**Comment by prasanna1211** [comment]
But for us we are going to use their Text component. We just need to wait till box is completed. After which we can use their text (understand their code first) to create our own.

**Comment by navin-moorthy** [comment]
Okay, this means we should wait until Box component is built for use.

**Comment by prasanna1211** [comment]
Yes.

**Comment by prasanna1211** [comment]
Closing this as it is merged
