### ISSUE TITLE
use-select tweaks

### ISSUE THREAD

**Issue by prasanna1211** [timelessco/chakra-components#54]
@navin-moorthy Add anything that you require on `use-select` here. I will start tweaking it properly 

Combobox
- [x] Scroll to selected item when opened. The selected item should be the first element in the popup
- [x] All options should be present when we first open the select [key]
- [x] On type scroll to the matching element and keep it at the top. Even though this will be by default, due to [key] point the behaviour changes and needs to be handled.
- [x] Handle out of bounds scrolling using keyboard
- [x] Down arrow behaviour is not same as onclick behaviour. Click, clears the text whereas down arrow doesn't
- [x] Backspace behaviour needs to be handled. Should clear one character when input in focus and entire when nothing is typed & a selected options is present & when dropdown is open.
- [x] Disabled option support
- [ ] Options based on API support
- [ ] Expose input ref for popper

ListBox
- [ ] Rapid typeahead
- [ ] scroll the element to the top of the window when the newly focused element is on top of the currently focused window. (Same for bottom)

**Comment by navin-moorthy** [comment]
@prasanna1211 I need the use-select to expose inputRef so that popper can use it as the anchorEl.

**Comment by prasanna1211** [comment]
@navin-moorthy I have fixed the use select to work with combobox. Updated the [codepen](https://codesandbox.io/s/quiet-butterfly-3z1qh) of whatever present in my local use select version. 

Fixes whatever is checked above.

**Comment by prasanna1211** [comment]
Closing this since it got cherry picked.
