### ISSUE TITLE
Install Commitizen

### ISSUE THREAD

**Issue by navin-moorthy** [timelessco/chakra-components#6]
Making our repo [commitizen](http://commitizen.github.io/cz-cli/) friendly

**Comment by navin-moorthy** [comment]
@prasanna1211 Commitizen is something new. 
Do we need to make our repo Commitizen friendly now.

**Comment by prasanna1211** [comment]
Yes @SamrithaS  has used it before I think. Helps in reading commits well. A good tool to go with.

**Comment by prasanna1211** [comment]
@SamrithaS  @govindsingh55  Refer this PR: Before closing mention the PR which solved it.
