### ISSUE TITLE
[ComboBox] Type Fixes in component

### ISSUE THREAD

**Issue by navin-moorthy** [timelessco/chakra-components#69]
There are a few open source standards that we generally do, even at times when certain things are obvious to avoid breaking the code. These are done generally when typescript is not used.

1. Type check once, for every function by `typeof x == 'function'`. Example, this shouldn't be an error. Instead a default filter function should load.
![image](https://user-images.githubusercontent.com/17434647/82045166-40084500-96cc-11ea-8882-d3bb2615cce7.png)

2. Same way for all functions. I could see this being there in the source at few places. Should extend it everywhere.

Originally posted at [issue](https://github.com/timelessco/chakra-components/issues/59#issuecomment-629181700)

**Comment by navin-moorthy** [comment]
Should we type check every props we get from outside the components?
![image](https://user-images.githubusercontent.com/39694575/82302132-cd9eaa00-99d6-11ea-873f-85a9b50a3529.png)

**Comment by navin-moorthy** [comment]
For options,
I have checked if the given options are Array of Object,
![image](https://user-images.githubusercontent.com/39694575/82307186-9f709880-99dd-11ea-816d-a299dcc4ecca.png)

I think it's the responsibility of those who use the component to give a valid opitons.
Now the component doesn't break on invalid values

**Comment by prasanna1211** [comment]
Yes, I agree with that. Just that ensure functions are covered for cases that don't break the component.

**Comment by navin-moorthy** [comment]
Sure, I am checking all the where the component can break because of the types and fixing it.

**Comment by navin-moorthy** [comment]
As per my knowledge, I have fixed most of the cased except for the below props,
![image](https://user-images.githubusercontent.com/39694575/82312255-6daf0000-99e4-11ea-8320-1b46ce45ed21.png)

I will keep this issue and pull request open until I write the docs and write examples using the above props.
